shiro:
  #选择使用的配置 authc,rememberMe,authz,cache
  remember_me: true
  cache:
    type: redis
    enabled: session

spring:
  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
    username: nzdev
    password: NZJRKJ_DEV
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    show-sql: true
    properties:
      #批量更新与插入
      jdbc:
        batch_size: 25
        order_inserts: true
        order_updates: true
    # only dev
    generate-ddl: true

  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/public/,classpath:/static/

  redis:
    # 使用数据库的索引编号，一个示例有16个数据库 0 到 15
    database: 0
    host: localhost
    port: 6379
    timeout: 3000
    jedis:
      pool:
        # 连接池的最大活动连接数量，使用负值无限制
        max-active: 8
        # 连接池的最大空闲连接数量，使用负值表示无限数量的空闲连接
        max-idle: 8
        # 最小空闲连接数量，使用正值才有效果
        min-idle: 0
        # 连接池最大阻塞等待时间，使用负值表示没有限制
        max-wait: -1ms

logging:
  level:
    com.payne: debug
