---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by DELL.
--- DateTime: 2019/12/2 11:21
---
local function zrangebyscore(queueKey,startTime,endTime)
    return redis.call('zrangebyscore',queueKey,startTime,endTime,'withScores');
end
local function zremrangebyrank(queueKey,startTime,endTime)
    redis.call('zremrangebyrank',queueKey,startTime,endTime);
end

local queueKey = KEYS[1];
local startTime = tonumber(ARGV[1]);
local endTime = tonumber(ARGV[2]);
local taskList = zrangebyscore(queueKey,startTime,endTime);
zremrangebyrank(queueKey,startTime,endTime);
return taskList;