---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by DELL.
--- DateTime: 2019/12/2 11:20
---
local function zadd(queueName,taskScore,taskId)
    redis.call('zadd',queueName,taskScore,taskId);
end

local queueName = KEYS[1];
local queueSize = KEYS[2];
for i= 1,queueSize ,2 do
   zadd(queueName,ARGV[i],ARGV[i+1]);
end
