spring:
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/public/,classpath:/static/
  redis:
    # 使用数据库的索引编号，一个示例有16个数据库 0 到 15
    database: 0
    host: localhost
    port: 6379
    timeout: 3000
    ssl: false
    # 对应 RedissonProperties 类
    #redisson:
      #config: classpath:/redisson/redisson.yml
